# Generated by Django 3.2.7 on 2021-09-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.TextField()),
                ('cloth_color', models.TextField()),
                ('cloth_img', models.ImageField(upload_to='media/cloth_img')),
            ],
        ),
        migrations.CreateModel(
            name='Human_model_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('img', models.ImageField(upload_to='media/data_annotation_hm')),
                ('mask', models.ImageField(upload_to='media/data_img_hm')),
            ],
        ),
    ]
