# Generated by Django 3.2.7 on 2021-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='made_cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_cloth_name', models.TextField()),
                ('made_cloth_color', models.TextField()),
                ('made_cloth_img', models.ImageField(upload_to='media/made_img')),
            ],
        ),
    ]
